{{- if .Values.isKurl -}}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service}}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8888
  selector:
    app: nginx
{{- else -}}
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service}}
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx
{{- end -}}
