apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: support-bundle
  name: {{ .Release.Name }}-support-bundle
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # This is the support bundle spec that will be used to generate the support bundle
  # Notes: we use {{ .Release.Namespace }} to ensure that the support bundle is scoped to the release namespace
  # We can use any of Helm's templating features here, including {{ .Values.someValue }}
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: support-bundle
    spec:
      collectors: 
        - logs:
           selector: 
             - app.kubernetes.io/name={{ .Chart.Name }}
           namespace: {{ .Release.Namespace }}
      analyzers:
        - deploymentStatus:
            name: nginx
            namespace: {{ .Release.Namespace }}
            outcomes:
              - fail:
                  when: "absent" # note that the "absent" failure state must be listed first if used.
                  message: The Nginx deployment is not present.
              - fail:
                  when: "< 1"
                  message: The Nginx deployment does not have any ready replicas.
              - warn:
                  when: "= 1"
                  message: The Nginx deployment has only a single ready replica.
              - pass:
                  message: There are multiple replicas of the API deployment ready.

