name: development

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

jobs:
  compatibility-matrix:
    strategy:
      fail-fast: false
      matrix:
        cluster: [ {distribution: kind, version: v1.27.0}]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          mkdir manifests2
          helm package . -u -d manifests2

      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/compatibility-actions/prepare-cluster@joshd/sc-86715/cluster-prepare-github-action
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          chart: manifests2/wordpress-enterprise-0.3.1.tgz
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          helm-chart-name: wordpress-enterprise