name: App Release

on:
  push:
    branches: [main]
    paths:
    - 'manifests/**/*'
    - 'templates/**/*'
    - Chart.yaml
    - '.github/workflows/release.yml'

jobs:
  create-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: 
          - slug: "wordpress-enterprise"
            dir: manifests
          - slug: "wordpress-express"
            dir: manifests2
        origins:
          - api: ""
            gql: ""
          - api: "https://api.staging.replicated.com/vendor"
            gql: "https://g.staging.replicated.com/graphql"

    steps:
    - uses: actions/checkout@v1
    - name: Get branch name
      run: echo GITHUB_BRANCH_NAME=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
      id: get_branch
    - name: Helm Package / deps
      run: "helm dependency update && helm package . -d manifests"
    - name: Create a wordpress-express release - stage directories
      run: "mkdir manifests2/ && cp manifests/*.tgz manifests2/"

    - name: prod/wordpress-enterprise - create release
      uses: docker://replicated/vendor-cli:latest
      with:
        args: release create --promote=Unstable --yaml-dir=${{ matrix.app.dir }}
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: ${{ matrix.app.slug }}
        REPLICATED_API_ORIGIN: ${{ matrix.origin.api }}
        REPLICATED_GRAPHQL_ORIGIN: ${{ matrix.origin.gql }}
