name: App Release

on:
  push:
    paths:
    - 'manifests/**/*'
    - 'templates/**/*'
    - Chart.yaml
    - '.github/workflows/release.yml'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get tag name, if specified
      run: if grep -q "/tags/" <<< "${GITHUB_REF}"; then echo ::set-output name=tag::${GITHUB_REF:10}; fi
      id: get_tag
    - name: Get branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: get_branch
    - name: Helm Package / deps
      run: "helm dependency update && helm package . -d manifests"

    - name: Create a wordpress-express release - stage directories
      run: "mkdir manifests2/ && cp manifests/*.tgz manifests2/"

    - name: prod/wordpress-enterprise - create release
      uses: docker://replicated/vendor-cli:latest
      with:
        args: release create --auto -y
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: wordpress-enterprise
        GITHUB_BRANCH_NAME: ${{ steps.get_branch.outputs.branch }}
        GITHUB_TAG_NAME: ${{ steps.get_tag.outputs.tag }}

    - name: staging/wordpress-enterprise - create release
      uses: docker://replicated/vendor-cli:latest
      with:
        args: release create --auto -y
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN_STAGING }}
        REPLICATED_APP: wordpress-enterprise
        GITHUB_BRANCH_NAME: ${{ steps.get_branch.outputs.branch }}
        GITHUB_TAG_NAME: ${{ steps.get_tag.outputs.tag }}
        REPLICATED_API_ORIGIN: https://api.staging.replicated.com/vendor
        REPLICATED_GRAPHQL_ORIGIN: https://g.staging.replicated.com/graphql

    - name: prod/wordpress-express - create release
      uses: docker://replicated/vendor-cli:latest
      with:
        args: release create --promote Unstable --yaml-dir=manifests2
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: wordpress-express
        GITHUB_BRANCH_NAME: ${{ steps.get_branch.outputs.branch }}
        GITHUB_TAG_NAME: ${{ steps.get_tag.outputs.tag }}



    - name: staging/wordpress-express - create release
      uses: docker://replicated/vendor-cli:latest
      with:
        args: release create --promote Unstable --yaml-dir=manifests2
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN_STAGING }}
        REPLICATED_APP: wordpress-express
        GITHUB_BRANCH_NAME: ${{ steps.get_branch.outputs.branch }}
        GITHUB_TAG_NAME: ${{ steps.get_tag.outputs.tag }}
        REPLICATED_API_ORIGIN: https://api.staging.replicated.com/vendor
        REPLICATED_GRAPHQL_ORIGIN: https://g.staging.replicated.com/graphql
